apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-app-get-href-from-10-websites
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"

spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /chamo/*
          pathType: Prefix
          backend:
            service:
              name: fastapi-app-get-href-from-10-websites
              port:
                number: 80
