apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: fastapi-app-get-href-from-10-websites
    spec:
      containers:
      - image: alvarolinarescabre/fastapi-app-get-href-from-10-websites:latest
        name: fastapi-app-get-href-from-10-websites
        ports:
        - containerPort: 80